export const countriesList = [
  { name: "Afghanistan", code: "AF" },
  { name: "Albania", code: "AL" },
  { name: "Algeria", code: "DZ" },
  { name: "American Samoa", code: "AS" },
  { name: "Andorra", code: "AD" },
  { name: "Angola", code: "AO" },
  { name: "Anguilla", code: "AI" },
  { name: "Antarctica", code: "AQ" },
  { name: "Antigua and Barbuda", code: "AG" },
  { name: "Argentina", code: "AR" },
  { name: "Armenia", code: "AM" },
  { name: "Aruba", code: "AW" },
  { name: "Australia", code: "AU" },
  { name: "Austria", code: "AT" },
  { name: "Azerbaijan", code: "AZ" },
  { name: "Bahamas", code: "BS" },
  { name: "Bahrain", code: "BH" },
  { name: "Bangladesh", code: "BD" },
  { name: "Barbados", code: "BB" },
  { name: "Belarus", code: "BY" },
  { name: "Belgium", code: "BE" },
  { name: "Belize", code: "BZ" },
  { name: "Benin", code: "BJ" },
  { name: "Bermuda", code: "BM" },
  { name: "Bhutan", code: "BT" },
  { name: "Bolivia", code: "BO" },
  { name: "Bonaire", code: "BQ" },
  { name: "Bosnia and Herzegovina", code: "BA" },
  { name: "Botswana", code: "BW" },
  { name: "Bouvet Island", code: "BV" },
  { name: "Brazil", code: "BR" },
  { name: "British Indian Ocean Territory", code: "IO" },
  { name: "Brunei Darussalam", code: "BN" },
  { name: "Bulgaria", code: "BG" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Burundi", code: "BI" },
  { name: "Cambodia", code: "KH" },
  { name: "Cameroon", code: "CM" },
  { name: "Canada", code: "CA" },
  { name: "Cape Verde", code: "CV" },
  { name: "Cayman Islands", code: "KY" },
  { name: "Central African Republic", code: "CF" },
  { name: "Chad", code: "TD" },
  { name: "Chile", code: "CL" },
  { name: "China", code: "CN" },
  { name: "Christmas Island", code: "CX" },
  { name: "Cocos (Keeling) Islands", code: "CC" },
  { name: "Colombia", code: "CO" },
  { name: "Comoros", code: "KM" },
  { name: "Congo", code: "CG" },
  { name: "Congo, The Democratic Republic of the", code: "CD" },
  { name: "Cook Islands", code: "CK" },
  { name: "Costa Rica", code: "CR" },
  { name: 'Cote D"Ivoire', code: "CI" },
  { name: "Croatia", code: "HR" },
  { name: "Cuba", code: "CU" },
  { name: "Curacao", code: "CW" },
  { name: "Cyprus", code: "CY" },
  { name: "Czech Republic", code: "CZ" },
  { name: "Denmark", code: "DK" },
  { name: "Djibouti", code: "DJ" },
  { name: "Dominica", code: "DM" },
  { name: "Dominican Republic", code: "DO" },
  { name: "Ecuador", code: "EC" },
  { name: "Egypt", code: "EG" },
  { name: "El Salvador", code: "SV" },
  { name: "Equatorial Guinea", code: "GQ" },
  { name: "Eritrea", code: "ER" },
  { name: "Estonia", code: "EE" },
  { name: "Eswatini", code: "SZ" },
  { name: "Ethiopia", code: "ET" },
  { name: "Falkland Islands (Malvinas)", code: "FK" },
  { name: "Faroe Islands", code: "FO" },
  { name: "Fiji", code: "FJ" },
  { name: "Finland", code: "FI" },
  { name: "France", code: "FR" },
  { name: "French Guiana", code: "GF" },
  { name: "French Polynesia", code: "PF" },
  { name: "French Southern Territories", code: "TF" },
  { name: "Gabon", code: "GA" },
  { name: "Gambia", code: "GM" },
  { name: "Georgia", code: "GE" },
  { name: "Germany", code: "DE" },
  { name: "Ghana", code: "GH" },
  { name: "Gibraltar", code: "GI" },
  { name: "Greece", code: "GR" },
  { name: "Greenland", code: "GL" },
  { name: "Grenada", code: "GD" },
  { name: "Guadeloupe", code: "GP" },
  { name: "Guam", code: "GU" },
  { name: "Guatemala", code: "GT" },
  { name: "Guernsey", code: "GG" },
  { name: "Guinea", code: "GN" },
  { name: "Guinea-Bissau", code: "GW" },
  { name: "Guyana", code: "GY" },
  { name: "Haiti", code: "HT" },
  { name: "Heard Island and Mcdonald Islands", code: "HM" },
  { name: "Holy See (Vatican City State)", code: "VA" },
  { name: "Honduras", code: "HN" },
  { name: "Hong Kong", code: "HK" },
  { name: "Hungary", code: "HU" },
  { name: "Iceland", code: "IS" },
  { name: "India", code: "IN" },
  { name: "Indonesia", code: "ID" },
  { name: "Iran, Islamic Republic Of", code: "IR" },
  { name: "Iraq", code: "IQ" },
  { name: "Ireland", code: "IE" },
  { name: "Isle of Man", code: "IM" },
  { name: "Israel", code: "IL" },
  { name: "Italy", code: "IT" },
  { name: "Ivory Coast", code: "CI" },
  { name: "Jamaica", code: "JM" },
  { name: "Japan", code: "JP" },
  { name: "Jersey", code: "JE" },
  { name: "Jordan", code: "JO" },
  { name: "Kazakhstan", code: "KZ" },
  { name: "Kenya", code: "KE" },
  { name: "Kiribati", code: "KI" },
  { name: 'Korea, Democratic People"S Republic of', code: "KP" },
  { name: "Korea, Republic of", code: "KR" },
  { name: "Kuwait", code: "KW" },
  { name: "Kyrgyzstan", code: "KG" },
  { name: 'Lao People"S Democratic Republic', code: "LA" },
  { name: "Laos", code: "LA" },
  { name: "Latvia", code: "LV" },
  { name: "Lebanon", code: "LB" },
  { name: "Lesotho", code: "LS" },
  { name: "Liberia", code: "LR" },
  { name: "Libyan Arab Jamahiriya", code: "LY" },
  { name: "Liechtenstein", code: "LI" },
  { name: "Lithuania", code: "LT" },
  { name: "Luxembourg", code: "LU" },
  { name: "Macao", code: "MO" },
  { name: "Macedonia, The Former Yugoslav Republic of", code: "MK" },
  { name: "Madagascar", code: "MG" },
  { name: "Malawi", code: "MW" },
  { name: "Malaysia", code: "MY" },
  { name: "Maldives", code: "MV" },
  { name: "Mali", code: "ML" },
  { name: "Malta", code: "MT" },
  { name: "Marshall Islands", code: "MH" },
  { name: "Martinique", code: "MQ" },
  { name: "Mauritania", code: "MR" },
  { name: "Mauritius", code: "MU" },
  { name: "Mayotte", code: "YT" },
  { name: "Mexico", code: "MX" },
  { name: "Micronesia, Federated States of", code: "FM" },
  { name: "Moldova, Republic of", code: "MD" },
  { name: "Monaco", code: "MC" },
  { name: "Mongolia", code: "MN" },
  { name: "Montenegro", code: "ME" },
  { name: "Montserrat", code: "MS" },
  { name: "Morocco", code: "MA" },
  { name: "Mozambique", code: "MZ" },
  { name: "Myanmar", code: "MM" },
  { name: "Namibia", code: "NA" },
  { name: "Nauru", code: "NR" },
  { name: "Nepal", code: "NP" },
  { name: "Netherlands", code: "NL" },
  { name: "Netherlands Antilles", code: "AN" },
  { name: "New Caledonia", code: "NC" },
  { name: "New Zealand", code: "NZ" },
  { name: "Nicaragua", code: "NI" },
  { name: "Niger", code: "NE" },
  { name: "Nigeria", code: "NG" },
  { name: "Niue", code: "NU" },
  { name: "Norfolk Island", code: "NF" },
  { name: "Northern Mariana Islands", code: "MP" },
  { name: "Norway", code: "NO" },
  { name: "Oman", code: "OM" },
  { name: "Pakistan", code: "PK" },
  { name: "Palau", code: "PW" },
  { name: "Palestinian Territory, Occupied", code: "PS" },
  { name: "Panama", code: "PA" },
  { name: "Papua New Guinea", code: "PG" },
  { name: "Paraguay", code: "PY" },
  { name: "Peru", code: "PE" },
  { name: "Philippines", code: "PH" },
  { name: "Pitcairn", code: "PN" },
  { name: "Poland", code: "PL" },
  { name: "Portugal", code: "PT" },
  { name: "Puerto Rico", code: "PR" },
  { name: "Qatar", code: "QA" },
  { name: "RWANDA", code: "RW" },
  { name: "Reunion", code: "RE" },
  { name: "Romania", code: "RO" },
  { name: "Russian Federation", code: "RU" },
  { name: "Saint Barthelemy", code: "BL" },
  { name: "Saint Helena", code: "SH" },
  { name: "Saint Kitts and Nevis", code: "KN" },
  { name: "Saint Lucia", code: "LC" },
  { name: "Saint Martin", code: "MF" },
  { name: "Saint Pierre and Miquelon", code: "PM" },
  { name: "Saint Vincent and the Grenadines", code: "VC" },
  { name: "Samoa", code: "WS" },
  { name: "San Marino", code: "SM" },
  { name: "Sao Tome and Principe", code: "ST" },
  { name: "Saudi Arabia", code: "SA" },
  { name: "Senegal", code: "SN" },
  { name: "Serbia", code: "RS" },
  { name: "Seychelles", code: "SC" },
  { name: "Sierra Leone", code: "SL" },
  { name: "Singapore", code: "SG" },
  { name: "Sint Maarten", code: "SX" },
  { name: "Slovakia", code: "SK" },
  { name: "Slovenia", code: "SI" },
  { name: "Solomon Islands", code: "SB" },
  { name: "Somalia", code: "SO" },
  { name: "South Africa", code: "ZA" },
  { name: "South Georgia and the South Sandwich Islands", code: "GS" },
  { name: "South Sudan", code: "SS" },
  { name: "Spain", code: "ES" },
  { name: "Sri Lanka", code: "LK" },
  { name: "Sudan", code: "SD" },
  { name: "Suriname", code: "SR" },
  { name: "Svalbard and Jan Mayen", code: "SJ" },
  { name: "Swaziland", code: "SZ" },
  { name: "Sweden", code: "SE" },
  { name: "Switzerland", code: "CH" },
  { name: "Syrian Arab Republic", code: "SY" },
  { name: "Taiwan", code: "TW" },
  { name: "Tajikistan", code: "TJ" },
  { name: "Tanzania, United Republic of", code: "TZ" },
  { name: "Thailand", code: "TH" },
  { name: "Timor-Leste", code: "TL" },
  { name: "Togo", code: "TG" },
  { name: "Tokelau", code: "TK" },
  { name: "Tonga", code: "TO" },
  { name: "Trinidad and Tobago", code: "TT" },
  { name: "Tunisia", code: "TN" },
  { name: "Türkiye", code: "TR" },
  { name: "Turkmenistan", code: "TM" },
  { name: "Turks and Caicos Islands", code: "TC" },
  { name: "Tuvalu", code: "TV" },
  { name: "Uganda", code: "UG" },
  { name: "Ukraine", code: "UA" },
  { name: "United Arab Emirates", code: "AE" },
  { name: "United Kingdom", code: "GB" },
  { name: "United States", code: "US" },
  { name: "United States Minor Outlying Islands", code: "UM" },
  { name: "Uruguay", code: "UY" },
  { name: "Uzbekistan", code: "UZ" },
  { name: "Vanuatu", code: "VU" },
  { name: "Venezuela", code: "VE" },
  { name: "Viet Nam", code: "VN" },
  { name: "Vietnam", code: "VN" },
  { name: "Virgin Islands, British", code: "VG" },
  { name: "Virgin Islands, U.S.", code: "VI" },
  { name: "Wallis and Futuna", code: "WF" },
  { name: "Western Sahara", code: "EH" },
  { name: "Yemen", code: "YE" },
  { name: "Zambia", code: "ZM" },
  { name: "Zimbabwe", code: "ZW" },
  { name: "Åland Islands", code: "AX" },
];

export const secondaryLanguagesList = [
  { value: "Abkhaz", label: "Abkhaz" },
  { value: "Afar", label: "Afar" },
  { value: "Afrikaans", label: "Afrikaans" },
  { value: "Akan", label: "Akan" },
  { value: "Albanian", label: "Albanian" },
  { value: "Amharic", label: "Amharic" },
  //   { value: "Arabic", label: "Arabic" },
  { value: "Aragonese", label: "Aragonese" },
  { value: "Armenian", label: "Armenian" },
  { value: "Assamese", label: "Assamese" },
  { value: "Avaric", label: "Avaric" },
  { value: "Avestan", label: "Avestan" },
  { value: "Aymara", label: "Aymara" },
  { value: "Azerbaijani", label: "Azerbaijani" },
  { value: "Bambara", label: "Bambara" },
  { value: "Bashkir", label: "Bashkir" },
  { value: "Basque", label: "Basque" },
  { value: "Belarusian", label: "Belarusian" },
  { value: "Bengali", label: "Bengali" },
  { value: "Bihari", label: "Bihari" },
  { value: "Bislama", label: "Bislama" },
  { value: "Bosnian", label: "Bosnian" },
  { value: "Breton", label: "Breton" },
  { value: "Bulgarian", label: "Bulgarian" },
  { value: "Burmese", label: "Burmese" },
  { value: "Catalan; Valencian", label: "Catalan; Valencian" },
  { value: "Chamorro", label: "Chamorro" },
  { value: "Chechen", label: "Chechen" },
  { value: "Chichewa; Chewa; Nyanja", label: "Chichewa; Chewa; Nyanja" },
  { value: "Chinese", label: "Chinese" },
  { value: "Chuvash", label: "Chuvash" },
  { value: "Cornish", label: "Cornish" },
  { value: "Corsican", label: "Corsican" },
  { value: "Cree", label: "Cree" },
  { value: "Croatian", label: "Croatian" },
  { value: "Czech", label: "Czech" },
  { value: "Danish", label: "Danish" },
  { value: "Divehi; Dhivehi; Maldivian;", label: "Divehi; Dhivehi; Maldivian" },
  //   { value: "Dutch", label: "Dutch" },
  // { value: "English", label: "English" },
  { value: "Esperanto", label: "Esperanto" },
  { value: "Estonian", label: "Estonian" },
  { value: "Ewe", label: "Ewe" },
  { value: "Faroese", label: "Faroese" },
  { value: "Fijian", label: "Fijian" },
  { value: "Finnish", label: "Finnish" },
  //   { value: "French", label: "French" },
  { value: "Fula; Fulah; Pulaar; Pular", label: "Fula; Fulah; Pulaar; Pular" },
  { value: "Galician", label: "Galician" },
  { value: "Georgian", label: "Georgian" },

  //   { value: "german", label: "German" },
  { value: "greek, modern", label: "Greek, Modern" },
  { value: "guaraní", label: "Guaraní" },
  { value: "gujarati", label: "Gujarati" },
  { value: "haitian; haitian creole", label: "Haitian; Haitian Creole" },
  { value: "hausa", label: "Hausa" },
  { value: "hebrew (modern)", label: "Hebrew (modern)" },
  { value: "herero", label: "Herero" },
  //   { value: "hindi", label: "Hindi" },
  { value: "hiri motu", label: "Hiri Motu" },
  { value: "hungarian", label: "Hungarian" },
  { value: "interlingua", label: "Interlingua" },
  { value: "indonesian", label: "Indonesian" },
  { value: "interlingue", label: "Interlingue" },
  { value: "irish", label: "Irish" },
  { value: "igbo", label: "Igbo" },
  { value: "inupiaq", label: "Inupiaq" },
  { value: "ido", label: "Ido" },
  { value: "icelandic", label: "Icelandic" },
  { value: "inuktitut", label: "Inuktitut" },
  { value: "japanese", label: "Japanese" },
  { value: "javanese", label: "Javanese" },
  { value: "kalaallisut, greenlandic", label: "Kalaallisut, Greenlandic" },
  { value: "kannada", label: "Kannada" },
  { value: "kanuri", label: "Kanuri" },
  { value: "kashmiri", label: "Kashmiri" },
  { value: "kazakh", label: "Kazakh" },
  { value: "khmer", label: "Khmer" },
  { value: "kikuyu, gikuyu", label: "Kikuyu, Gikuyu" },
  { value: "kinyarwanda", label: "Kinyarwanda" },
  { value: "kirghiz, kyrgyz", label: "Kirghiz, Kyrgyz" },
  { value: "komi", label: "Komi" },
  { value: "kongo", label: "Kongo" },
  { value: "korean", label: "Korean" },
  { value: "kurdish", label: "Kurdish" },
  { value: "kwanyama, kuanyama", label: "Kwanyama, Kuanyama" },
  { value: "latin", label: "Latin" },
  {
    value: "luxembourgish, letzeburgesch",
    label: "Luxembourgish, Letzeburgesch",
  },
  { value: "luganda", label: "Luganda" },
  {
    value: "limburgish, limburgan, limburger",
    label: "Limburgish, Limburgan, Limburger",
  },
  { value: "lingala", label: "Lingala" },
  { value: "lao", label: "Lao" },
  { value: "lithuanian", label: "Lithuanian" },
  { value: "latvian", label: "Latvian" },
  { value: "manx", label: "Manx" },
  { value: "macedonian", label: "Macedonian" },
  { value: "malagasy", label: "Malagasy" },
  { value: "malay", label: "Malay" },
  { value: "malayalam", label: "Malayalam" },
  { value: "maltese", label: "Maltese" },
  { value: "māori", label: "Māori" },
  { value: "marathi (marāṭhī)", label: "Marathi (Marāṭhī)" },
  { value: "marshallese", label: "Marshallese" },
  { value: "mongolian", label: "Mongolian" },
  { value: "nauru", label: "Nauru" },
  { value: "navajo, navaho", label: "Navajo, Navaho" },
  { value: "norwegian bokmål", label: "Norwegian Bokmål" },
  { value: "north ndebele", label: "North Ndebele" },
  { value: "nepali", label: "Nepali" },
  { value: "ndonga", label: "Ndonga" },
  { value: "norwegian nynorsk", label: "Norwegian Nynorsk" },
  { value: "norwegian", label: "Norwegian" },
  { value: "nuosu", label: "Nuosu" },
  { value: "south ndebele", label: "South Ndebele" },
  { value: "occitan", label: "Occitan" },
  { value: "ojibwe, ojibwa", label: "Ojibwe, Ojibwa" },
  {
    value:
      "old church slavonic, church slavic, church slavonic, old bulgarian, old slavonic",
    label:
      "Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic",
  },
  { value: "oromo", label: "Oromo" },
  { value: "oriya", label: "Oriya" },
  { value: "ossetian, ossetic", label: "Ossetian, Ossetic" },
  { value: "panjabi, punjabi", label: "Panjabi, Punjabi" },
  { value: "pāli", label: "Pāli" },
  { value: "persian", label: "Persian" },
  { value: "polish", label: "Polish" },
  { value: "pashto, pushto", label: "Pashto, Pushto" },
  //   { value: "portuguese", label: "Portuguese" },
  { value: "quechua", label: "Quechua" },
  { value: "romansh", label: "Romansh" },
  { value: "kirundi", label: "Kirundi" },
  {
    value: "romanian, moldavian, moldovan",
    label: "Romanian, Moldavian, Moldovan",
  },
  { value: "russian", label: "Russian" },
  { value: "sanskrit (saṁskṛta)", label: "Sanskrit (Saṁskṛta)" },
  { value: "sardinian", label: "Sardinian" },
  { value: "sindhi", label: "Sindhi" },
  { value: "northern sami", label: "Northern Sami" },
  { value: "samoan", label: "Samoan" },
  { value: "sango", label: "Sango" },
  { value: "serbian", label: "Serbian" },
  { value: "scottish gaelic; gaelic", label: "Scottish Gaelic; Gaelic" },
  { value: "shona", label: "Shona" },
  { value: "sinhala, sinhalese", label: "Sinhala, Sinhalese" },
  { value: "slovak", label: "Slovak" },
  { value: "slovene", label: "Slovene" },
  { value: "somali", label: "Somali" },
  { value: "southern sotho", label: "Southern Sotho" },
  //   { value: "spanish; castilian", label: "Spanish; Castilian" },
  { value: "sundanese", label: "Sundanese" },
  { value: "swahili", label: "Swahili" },
  { value: "swati", label: "Swati" },
  { value: "swedish", label: "Swedish" },
  { value: "tamil", label: "Tamil" },
  { value: "telugu", label: "Telugu" },
  { value: "tajik", label: "Tajik" },
  { value: "thai", label: "Thai" },
  { value: "tigrinya", label: "Tigrinya" },
  {
    value: "tibetan standard, tibetan, central",
    label: "Tibetan Standard, Tibetan, Central",
  },
  { value: "turkmen", label: "Turkmen" },
  { value: "tagalog", label: "Tagalog" },
  { value: "tswana", label: "Tswana" },
  { value: "tonga (tonga islands)", label: "Tonga (Tonga Islands)" },
  { value: "turkish", label: "Turkish" },
  { value: "tsonga", label: "Tsonga" },
  { value: "tatar", label: "Tatar" },
  { value: "twi", label: "Twi" },
  { value: "tahitian", label: "Tahitian" },
  { value: "uighur, uyghur", label: "Uighur, Uyghur" },
  { value: "ukrainian", label: "Ukrainian" },
  //   { value: "urdu", label: "Urdu" },
  { value: "uzbek", label: "Uzbek" },
  { value: "venda", label: "Venda" },
  { value: "vietnamese", label: "Vietnamese" },
  { value: "volapük", label: "Volapük" },
  { value: "walloon", label: "Walloon" },
  { value: "welsh", label: "Welsh" },
  { value: "wolof", label: "Wolof" },
  { value: "western frisian", label: "Western Frisian" },
  { value: "xhosa", label: "Xhosa" },
  { value: "yiddish", label: "Yiddish" },
  { value: "yoruba", label: "Yoruba" },
  { value: "zhuang, chuang", label: "Zhuang, Chuang" },
];

export const primaryLanguagesList = [
  "French",
  "German",
  "Spanish",
  "Mandarin",
  "Italian",
  "Dutch",
  "Portuguese",
  "Arabic",
  "Hindi",
  "Urdu",
];

export const toggleFormVariant = {
  open: {
    height: "auto",
    opacity: 1,
    y: 0,
    transition: {
      duration: 0.5,
    },
  },
  closed: {
    height: 0,
    opacity: 0,
    y: "-100%",
    transition: {
      duration: 0.7,
    },
  },
};
